QueryBuilderASP/QueryBuilderMVC/Controllers/FeaturesController.cs
using System.Web.Mvc;

namespace QueryBuilderMVC.Controllers
{
    public class FeaturesController : Controller
    {
        // GET: Features
        public ActionResult NoRegistration()
        {
            ViewBag.Message = "Query Builder can use without registration. For use just press 'START FREE'."+
                " Query Builder without registration have features such us:";

            return View();
        }

        public ActionResult ExportData()
        {
            ViewBag.Message = "Opportunity to export result for your query in *.XLS and *.PDF. Your data will be save to popular format files on your PC or send to e-mail.";
            return View();
        }

        public ActionResult SharedProject()
        {
            ViewBag.Message = "You have the ability to share your project with colleagues and build queries together or just give someone access requests in your project.";
            return View();
        }

        public ActionResult ER_Model()
        {
            ViewBag.Message = "You have the opportunity to see a detailed ER-model of your database." +
            " The ER-model will help you to trace all the connections and relationships of tables, as well as the available fields.";
            return View();
        }

        public ActionResult BuildQuery()
        {
            ViewBag.Message = "The ability to build your requests only with the mouse. You do not need to know the SQL to build your query and get results." +
            " For this will be enough to use our intuitive graphical interface.";
            return View();
        }
        public ActionResult TypesQuery()
        {
            ViewBag.Message = "The ability to build various types of queries, requests and combine to make nested queries.Complex queries are now easy to build.";
            return View();
        }
    }
}

QueryBuilderASP/QueryBuilderMVC/Controllers/HomeController.cs
using System.Web.Mvc;
using System.Web;
using System;
using System.Collections.Generic;
using QueryBuilderMVC.Filters;

namespace QueryBuilderMVC.Controllers
{
    [RequireHttps]
    [Culture]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            //using (var context = new UniversityContext())
            //{
            //    var courses = context.Courses.ToList();
            //}

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult WPF()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult ChangeCulture(string lang)
        {
            string returnUrl = Request.UrlReferrer.AbsolutePath;
            // Список культур
            List<string> cultures = new List<string>() { "ru", "en", "de" };
            if (!cultures.Contains(lang))
            {
                lang = "en";
            }
            // Сохраняем выбранную культуру в куки
            HttpCookie cookie = Request.Cookies["lang"];
            if (cookie != null)
                cookie.Value = lang;   // если куки уже установлено, то обновляем значение
            else
            {

                cookie = new HttpCookie("lang");
                cookie.HttpOnly = false;
                cookie.Value = lang;
                cookie.Expires = DateTime.Now.AddYears(1);
            }
            Response.Cookies.Add(cookie);
            return Redirect(returnUrl);
        }
    }
}

QueryBuilderASP/QueryBuilderMVC/Controllers/WorkflowController.cs
using System;
using System.Web.Mvc;
using QueryBuilder.DAL.Models;
using QueryBuilderMVC.Models;
using Microsoft.AspNet.Identity;
using System.Linq;
using AutoMapper;
using QueryBuilder.Services.Contracts;
using System.Collections.Generic;
using System.Data;
using System.Web.Configuration;
using QueryBuilder.Constants;
using QueryBuilder.Utils.Mailers;
using QueryBuilder.Utils.Encryption;
using Newtonsoft.Json;
using System.IO;
using System.Text;
using QueryBuilderMVC.Filters;
using System.Text.RegularExpressions;
using QueryBuilder.Constants.DbConstants;
using QueryBuilder.Utils.DBSchema;
using QueryBuilder.Utils.Exporters;
using System.Web;

namespace QueryBuilderMVC.Controllers
{
    [Culture]
    public class WorkflowController : Controller
    {
        private readonly IProjectService _serviceProject;
        private readonly IUserService _serviceUser;
        private readonly IConnectionDbService _serviceConnection;
        private readonly IProjectsShareService _serviceProjectsShareService;
        private readonly IQueryService _serviceQuery;
		private readonly IQueriesHistoryService _serviceQueryHistory;

		private readonly ProjectViewModel _projectModel = new ProjectViewModel();
        private readonly ConnectionViewModel _connectionModel = new ConnectionViewModel();
		private readonly QueryViewModel _queryModel = new QueryViewModel();
		private readonly QueryHistoryViewModel _queryHistoryModel = new QueryHistoryViewModel();

		private readonly ProjectsListViewModel _projectListModel = new ProjectsListViewModel();
        private ApplicationUser _currentUser;

        public WorkflowController(IProjectService serviceProject, IUserService serviceUser,
            IProjectsShareService serviceProjectsShare, IConnectionDbService serviceConnection, 
            IQueryService serviceQueryService, IQueriesHistoryService serviceQueryHistory)
        {
            _serviceProject = serviceProject;
            _serviceUser = serviceUser;
            _serviceConnection = serviceConnection;
            _serviceProjectsShareService = serviceProjectsShare;
			_serviceQuery = serviceQueryService;
			_serviceQueryHistory = serviceQueryHistory;
		}

        [HttpGet]
        public ActionResult List(string id = "0")
        {
            
            if (User.Identity.IsAuthenticated)
            {
                _currentUser = _serviceUser.GetUserByID(User.Identity.GetUserId());
                var projects = _serviceProjectsShareService.GetUserProjects(_currentUser);
                var projectsViewModel = Mapper.Map<IEnumerable<Project>, IEnumerable<ProjectsListViewModel>>(projects).ToList();
                var countInvited = 0;
                foreach (var project in projectsViewModel)
                {
                    project.UserRole = _serviceProjectsShareService.GetUserRole(_currentUser, project.ProjectID);
                    project.CountUsersForShared = _serviceProjectsShareService.GetUsersForSharedProject(_serviceProject.GetProject(project.ProjectID)).Count();
                    if (project.UserRole == 0)
                    {
                        countInvited++;
                    }
                }

                ViewBag.CountInvited = countInvited;
                _projectModel.Projects = projectsViewModel;
                _projectModel.IdCurrentProject = Convert.ToInt32(id);
                if (id != "0")
                {
                    if (Request.Cookies[".AspNet.ApplicationCookie"] != null)
                    {
                        var cookie = new HttpCookie(".AspNet.ApplicationCookie")
                        {
                            Expires = DateTime.Now.AddDays(-1d)
                            
                        };
                        Response.Cookies.Add(cookie);
                    }

                    Session["datatableForGrid"] = new DataTable();

                    var connectionsCurrentProject = _serviceConnection.GetConnectionDBs(_projectModel.IdCurrentProject);
                    _projectModel.ConnectionDbs = Mapper.Map<IEnumerable<ConnectionDB>, IEnumerable<ConnectionsListViewModel>>(connectionsCurrentProject).ToList();
                    
                    if (_projectModel.ConnectionDbs.Any())
                    {
                        var connect = _projectModel.ConnectionDbs.First();
                        var sqlConnection =
                            $"Data source= {connect.ServerName}; Initial catalog= {connect.DatabaseName}; UID= {connect.LoginDB}; Password= {Rijndael.DecryptStringFromBytes(connect.PasswordDB)};";
                        ViewBag.ConnectionString = sqlConnection;
                    }

					var quriesCurrentProject = _serviceQuery.GetQueries(_projectModel.IdCurrentProject);
					_projectModel.Queries = Mapper.Map<IEnumerable<Query>, IEnumerable<QueryListViewModel>>(quriesCurrentProject).ToList();

					var historyCurrentProject = _serviceQueryHistory.GetQueriesHistory(_projectModel.IdCurrentProject);
					_projectModel.QueryHistory = Mapper.Map<IEnumerable<QueryHistory>, IEnumerable<QueryHistoryListViewModel>>(historyCurrentProject).ToList();

					var currentProject = _serviceProject.GetProject(_projectModel.IdCurrentProject);
                    if (currentProject != null)
                    {
                        ViewBag.name = currentProject.ProjectName;
                        ViewBag.desk = currentProject.ProjectDescription;
                    }
                    ViewBag.Count = _projectModel.ConnectionDbs.Count();

                    if (ViewBag.Count == 0)
                    {
                        ViewBag.ConnectionName = "ConnectionName";
                        ViewBag.DatabaseName = "connections.DatabaseName";
                        ViewBag.ServerName = "ServerName";
                    }

                }
                else
                {
                    ViewBag.name = "choose project";
                    ViewBag.desk = "No description";
                    ViewBag.ConnectionName = "ConnectionName";
                    ViewBag.DatabaseName = "DatabaseName";
                    ViewBag.ServerName = "ServerName";
                }

                return View(_projectModel);
            }
            else
            {
                return View(GetExampleProject());
            }

        }

        public ActionResult ListProjectPartial()
        {
            var countInvited = 0;
            if (User.Identity.IsAuthenticated)
            {
                _currentUser = _serviceUser.GetUserByID(User.Identity.GetUserId());
                var projects = _serviceProjectsShareService.GetUserProjects(_currentUser);
                var projectsViewModel = Mapper.Map<IEnumerable<Project>, IEnumerable<ProjectsListViewModel>>(projects).ToList();
                foreach (var project in projectsViewModel)
                {
                    project.CountUsersForShared = _serviceProjectsShareService.GetUsersForSharedProject(_serviceProject.GetProject(project.ProjectID)).Count();
                    project.UserRole = _serviceProjectsShareService.GetUserRole(_currentUser, project.ProjectID);
                    if (project.UserRole == 0)
                    {
                        countInvited++;
                    }
                }
                _projectModel.Projects = projectsViewModel;
                ViewBag.CountInvited = countInvited;

                return PartialView("ListProjectPartial", _projectModel);
            }
            else
            {
                countInvited = 1;
                ViewBag.CountInvited = countInvited;
                return PartialView("ListProjectPartial", GetExampleProject());
            }

        }

        public ActionResult QueryBuilderPartial()
        {
            string PreviousPage = "http://stackoverflow.com/1";
            _currentUser = _serviceUser.GetUserByID(User.Identity.GetUserId());
            if (System.Web.HttpContext.Current != null)
            {
                PreviousPage = System.Web.HttpContext.Current.Request.UrlReferrer.ToString();
            }
            string pattern = "[0-9]+$";
            Regex rgx = new Regex(pattern, RegexOptions.IgnoreCase);
            Match match = rgx.Match(PreviousPage);
            int id = Convert.ToInt16(match.Value);
            _projectModel.IdCurrentProject = id;
            if (id != 0)
            {
                var connectionsCurrentProject = _serviceConnection.GetConnectionDBs(_projectModel.IdCurrentProject);
                _projectModel.ConnectionDbs = Mapper.Map<IEnumerable<ConnectionDB>, IEnumerable<ConnectionsListViewModel>>(connectionsCurrentProject).ToList();

                if (_projectModel.ConnectionDbs.Any())
                {
                    var connect = _projectModel.ConnectionDbs.First();
                    var sqlConnection =
                        $"Data source= {connect.ServerName}; Initial catalog= {connect.DatabaseName}; UID= {connect.LoginDB}; Password= {Rijndael.DecryptStringFromBytes(connect.PasswordDB)};";
                    ViewBag.ConnectionString = sqlConnection;
                }

            }
            else
            {
                return PartialView("QueryBuilderPartial", GetExampleProject());
            }
                return PartialView("QueryBuilderPartial", _projectModel);
        }

        public ProjectViewModel GetExampleProject()
        {
            var proj = new List<ProjectsListViewModel>
                {

                    new ProjectsListViewModel
                    {
                        ProjectID = 1,
                        ProjectName = "Example",
                        ProjectDescription = "This project for demonstration service",
                        UserRole = UserRoleProjectsShareConstants.Owner,
                     }

                };
            var connect = new List<ConnectionsListViewModel>
                {
                    new ConnectionsListViewModel

QueryBuilderASP/QueryBuilderMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

QueryBuilderASP/QueryBuilderMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

QueryBuilderASP/QueryBuilderMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = Resources.Resource.IndexTitle;
}




<link rel="stylesheet" type="text/css" href="../../Content/parallax-slider/parallax-slider.css" />
<link rel="stylesheet" type="text/css" href="../../Content/parallax-slider/flexslider.css" />
<script type="text/javascript" src="~/Scripts/modernizr.custom.28468.js"></script>




<!-- Sequence Modern Slider -->
<div id="da-slider" class="da-slider">

    <div class="da-slide">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2>
                        <i>@Resources.Resource.IndexTextErModel</i>
                        <br>
                        <i>@Resources.Resource.IndexTextYOUR</i>
                        <br>
                        <i>@Resources.Resource.IndexTextDATABASE</i>
                    </h2>
                    <p>
                        <i>@Resources.Resource.IndexTextAboutErModel1 </i>
                        <br />
                        <i>@Resources.Resource.IndexTextAboutErModel2</i>
                    </p>
                    @Html.ActionLink(Resources.Resource.IndexStartFREE, "List", "Workflow", new { area = "" }, new { @class = "btn btn-info btn-lg da-link" })
                    <div class="da-img">
                        <img src="../../Images/parallax-slider/images/2.png" alt="image01" />
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="da-slide">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2>
                        <i>@Resources.Resource.IndexTextEXPORTDATA</i>
                        <br />
                        <i>@Resources.Resource.IndexTextToPDF</i>
                        <br />
                        <i>@Resources.Resource.IndexTextAndExcel</i>
                    </h2>
                    <p>
                        <i>@Resources.Resource.IndexTextAboutExportData1</i>
                        <br />
                        <i>@Resources.Resource.IndexTextAboutExportData2</i>
                    </p>
                    @Html.ActionLink(Resources.Resource.IndexStartFREE, "List", "Workflow", new { area = "" }, new { @class = "btn btn-info btn-lg da-link" })
                    <div class="da-img">
                        <img src="../../Images/parallax-slider/images/3.png" alt="image01" />
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="da-slide">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2>
                        <i>@Resources.Resource.IndexTextShared</i>
                        </br>
                        <i>@Resources.Resource.IndexTextProject</i>
                       
                    </h2>
                    <p>
                        <i>@Resources.Resource.IndexTextAboutShared1</i>
                        <br />
                        <i>@Resources.Resource.IndexTextAboutShared2</i>
                        <br />
                        <i>@Resources.Resource.IndexTextAboutShared3</i>
                    </p>
                    @Html.ActionLink(Resources.Resource.IndexStartFREE, "List", "Workflow", new { area = "" }, new { @class = "btn btn-info btn-lg da-link" })
                    <div class="da-img">
                        <img src="../../Images/parallax-slider/images/1.png" alt="image01" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <nav class="da-arrows">
        <span class="da-arrows-prev">
        </span>
        <span class="da-arrows-next">
        </span>
    </nav>
</div>




<script src="~/Scripts/jquery-1.8.3.min.js">
</script>

<script type="text/javascript" src="~/Scripts/jquery.cslider.js"></script>




<script type="text/javascript" src="~/Scripts/jquery.cslider.js">
</script>
<script type="text/javascript">
    $(function () {

        $('#da-slider').cslider({
            autoplay: true,
            bgincrement: 100
        });

    });
</script>



<div class="container">
    <div class="row mar-b-50">
        <div class="col-md-12">
            <div class="text-center feature-head wow fadeInDown">
                <h1 class="">
                    @Resources.Resource.IndexTextWelcome
                </h1>

            </div>


            <div class="feature-box">
                <div class="col-md-4 col-sm-4 text-center wow fadeInUp">
                    <div class="feature-box-heading">
                        <em>
                            <img src="~/Images/tag.png" alt="Quick start" width="100" height="100">

                        </em>
                        <h4>
                            <b>@Resources.Resource.IndexTextGettingStarted</b>
                        </h4>
                    </div>
                    <p class="text-center">
                        @Resources.Resource.IndexTextGettinStartedText
                    </p>
                    @Html.ActionLink(Resources.Resource.IndexTextMore, "NoRegistration", "Features", new { area = "" }, new { @class = "btn btn-default" })


                </div>
                <div class="col-md-4 col-sm-4 text-center wow fadeInUp">
                    <div class="feature-box-heading">
                        <em>
                            <img src="~/Images/quickoffice32.png" alt="Build query" width="100" height="100">
                        </em>
                        <h4>
                            <b>@Resources.Resource.IndexTextBuildQuery</b>
                        </h4>
                    </div>
                    <p class="text-center">
                        @Resources.Resource.IndexTextBuildQueryText
                    </p>
                    @Html.ActionLink(Resources.Resource.IndexTextMore, "BuildQuery", "Features", new { area = "" }, new { @class = "btn btn-default" })

                </div>
                <div class="col-md-4 col-sm-4 text-center wow fadeInUp">
                    <div class="feature-box-heading">
                        <em>
                            <img src="~/Images/analytics16.png" alt="ER-model your database" width="100" height="100">
                        </em>
                        <h4>
                            <b>@Resources.Resource.IndexTextER </b>
                        </h4>
                    </div>
                    <p class="text-center">
                        @Resources.Resource.IndexTextERText
                    </p>
                    @Html.ActionLink(Resources.Resource.IndexTextMore, "ER_Model", "Features", new { area = "" }, new { @class = "btn btn-default" })

                </div>
            </div>

            <div class="col-md-4 col-sm-4 text-center wow fadeInUp">
                <div class="feature-box-heading">
                    <em>
                        <img src="~/Images/acrobat.png" alt="Export data" width="100" height="100">

                    </em>
                    <h4>
                        <b>@Resources.Resource.IndexTextExportDataSmall</b>
                    </h4>
                </div>
                <p class="text-center">
                    @Resources.Resource.IndexTextExportDataText
                </p>
                @Html.ActionLink(Resources.Resource.IndexTextMore, "ExportData", "Features", new { area = "" }, new { @class = "btn btn-default" })

            </div>
            <div class="col-md-4 col-sm-4 text-center wow fadeInUp">
                <div class="feature-box-heading">
                    <em>
                        <img src="~/Images/groups16.png" alt="Shared project" width="100" height="100">
                    </em>
                    <h4>
                        <b>@Resources.Resource.IndexTextSharedProject </b>
                    </h4>
                </div>
                <p class="text-center">
                    @Resources.Resource.IndexTextSharedProjectText
                </p>
                @Html.ActionLink(Resources.Resource.IndexTextMore, "SharedProject", "Features", new { area = "" }, new { @class = "btn btn-default" })
            </div>
            <div class="col-md-4 col-sm-4 text-center wow fadeInUp">
                <div class="feature-box-heading">
                    <em>
                        <img src="~/Images/compute.png" alt="Queries" width="100" height="100">
                    </em>
                    <h4>
                        <b>@Resources.Resource.IndexTextQueries</b>
                    </h4>
                </div>
                <p class="text-center">
                    @Resources.Resource.IndexTextQueriesText
                </p>
                @Html.ActionLink(Resources.Resource.IndexTextMore, "TypesQuery", "Features", new { area = "" }, new { @class = "btn btn-default" })
            </div>
        </div>


        <!--feature end-->
    </div>
</div>