QueryBuilderASP/QueryBuilderMVC/Controllers/BuilderController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using QueryBuilderMVC.Models;
using System.Data.SqlClient;
using QueryBuilder.Services.Contracts;
using QueryBuilder.Utils.Encryption;
using System.Configuration;

namespace QueryBuilderMVC.Controllers
{
    public class BuilderController : Controller
    {
        private readonly IConnectionDbService _serviceConnection;

        public BuilderController(IConnectionDbService serviceConnection)
        {
            _serviceConnection = serviceConnection;
        }


        // GET: Builder
        [HttpGet]
        public ActionResult ERModel(int id = 0)
        {
            if (id != 0)
            {
                string sqlConnection="";

                if (id == -1)
                {
                    //sqlConnection = System.Web.Configuration.WebConfigurationManager.OpenWebConfiguration("/MyWebSiteRoot").ConnectionStrings.ConnectionStrings["NorthwindConnection"].ConnectionString;
                    sqlConnection = ConfigurationManager.ConnectionStrings["TestConnection"].ConnectionString;
                    //sqlConnection = "Data Source =.\\v11; AttachDbFilename=| DataDirectory |NORTHWND.MDF; Integrated Security= True";
                }
                else
                {
                    var Connection = _serviceConnection.GetConnectionDb(id);

                    sqlConnection = String.Format("Data source= {0}; Initial catalog= {1}; UID= {2}; Password= {3};",
                   Connection.ServerName, Connection.DatabaseName, Connection.LoginDB, Rijndael.DecryptStringFromBytes(Connection.PasswordDB));
                }
                var sql = new SqlConnection(sqlConnection);

                var viewmodel = new ERModelViewModel(sql);
                return View(viewmodel);
            }
            else
            {
                return RedirectToAction("List", "Workflow");
            }
        }

        public JsonResult GetDBModel(string connectionString)
		{
			var movies = new List<object>();
			
			

			return Json(movies, JsonRequestBehavior.AllowGet);

		}
    }
}

QueryBuilderASP/QueryBuilderMVC/Controllers/WorkflowController.cs
using System;
using System.Web.Mvc;
using QueryBuilder.DAL.Models;
using QueryBuilderMVC.Models;
using Microsoft.AspNet.Identity;
using System.Linq;
using AutoMapper;
using QueryBuilder.Services.Contracts;
using System.Collections.Generic;
using System.Data;
using System.Web.Configuration;
using QueryBuilder.Constants;
using QueryBuilder.Utils.Mailers;
using QueryBuilder.Utils.Encryption;
using Newtonsoft.Json;
using System.IO;
using System.Text;
using QueryBuilderMVC.Filters;
using System.Text.RegularExpressions;
using QueryBuilder.Constants.DbConstants;
using QueryBuilder.Utils.DBSchema;
using QueryBuilder.Utils.Exporters;
using System.Web;

namespace QueryBuilderMVC.Controllers
{
    [Culture]
    public class WorkflowController : Controller
    {
        private readonly IProjectService _serviceProject;
        private readonly IUserService _serviceUser;
        private readonly IConnectionDbService _serviceConnection;
        private readonly IProjectsShareService _serviceProjectsShareService;
        private readonly IQueryService _serviceQuery;
		private readonly IQueriesHistoryService _serviceQueryHistory;

		private readonly ProjectViewModel _projectModel = new ProjectViewModel();
        private readonly ConnectionViewModel _connectionModel = new ConnectionViewModel();
		private readonly QueryViewModel _queryModel = new QueryViewModel();
		private readonly QueryHistoryViewModel _queryHistoryModel = new QueryHistoryViewModel();

		private readonly ProjectsListViewModel _projectListModel = new ProjectsListViewModel();
        private ApplicationUser _currentUser;

        public WorkflowController(IProjectService serviceProject, IUserService serviceUser,
            IProjectsShareService serviceProjectsShare, IConnectionDbService serviceConnection, 
            IQueryService serviceQueryService, IQueriesHistoryService serviceQueryHistory)
        {
            _serviceProject = serviceProject;
            _serviceUser = serviceUser;
            _serviceConnection = serviceConnection;
            _serviceProjectsShareService = serviceProjectsShare;
			_serviceQuery = serviceQueryService;
			_serviceQueryHistory = serviceQueryHistory;
		}

        [HttpGet]
        public ActionResult List(string id = "0")
        {
            
            if (User.Identity.IsAuthenticated)
            {
                _currentUser = _serviceUser.GetUserByID(User.Identity.GetUserId());
                var projects = _serviceProjectsShareService.GetUserProjects(_currentUser);
                var projectsViewModel = Mapper.Map<IEnumerable<Project>, IEnumerable<ProjectsListViewModel>>(projects).ToList();
                var countInvited = 0;
                foreach (var project in projectsViewModel)
                {
                    project.UserRole = _serviceProjectsShareService.GetUserRole(_currentUser, project.ProjectID);
                    project.CountUsersForShared = _serviceProjectsShareService.GetUsersForSharedProject(_serviceProject.GetProject(project.ProjectID)).Count();
                    if (project.UserRole == 0)
                    {
                        countInvited++;
                    }
                }

                ViewBag.CountInvited = countInvited;
                _projectModel.Projects = projectsViewModel;
                _projectModel.IdCurrentProject = Convert.ToInt32(id);
                if (id != "0")
                {
                    if (Request.Cookies[".AspNet.ApplicationCookie"] != null)
                    {
                        var cookie = new HttpCookie(".AspNet.ApplicationCookie")
                        {
                            Expires = DateTime.Now.AddDays(-1d)
                            
                        };
                        Response.Cookies.Add(cookie);
                    }

                    Session["datatableForGrid"] = new DataTable();

                    var connectionsCurrentProject = _serviceConnection.GetConnectionDBs(_projectModel.IdCurrentProject);
                    _projectModel.ConnectionDbs = Mapper.Map<IEnumerable<ConnectionDB>, IEnumerable<ConnectionsListViewModel>>(connectionsCurrentProject).ToList();
                    
                    if (_projectModel.ConnectionDbs.Any())
                    {
                        var connect = _projectModel.ConnectionDbs.First();
                        var sqlConnection =
                            $"Data source= {connect.ServerName}; Initial catalog= {connect.DatabaseName}; UID= {connect.LoginDB}; Password= {Rijndael.DecryptStringFromBytes(connect.PasswordDB)};";
                        ViewBag.ConnectionString = sqlConnection;
                    }

					var quriesCurrentProject = _serviceQuery.GetQueries(_projectModel.IdCurrentProject);
					_projectModel.Queries = Mapper.Map<IEnumerable<Query>, IEnumerable<QueryListViewModel>>(quriesCurrentProject).ToList();

					var historyCurrentProject = _serviceQueryHistory.GetQueriesHistory(_projectModel.IdCurrentProject);
					_projectModel.QueryHistory = Mapper.Map<IEnumerable<QueryHistory>, IEnumerable<QueryHistoryListViewModel>>(historyCurrentProject).ToList();

					var currentProject = _serviceProject.GetProject(_projectModel.IdCurrentProject);
                    if (currentProject != null)
                    {
                        ViewBag.name = currentProject.ProjectName;
                        ViewBag.desk = currentProject.ProjectDescription;
                    }
                    ViewBag.Count = _projectModel.ConnectionDbs.Count();

                    if (ViewBag.Count == 0)
                    {
                        ViewBag.ConnectionName = "ConnectionName";
                        ViewBag.DatabaseName = "connections.DatabaseName";
                        ViewBag.ServerName = "ServerName";
                    }

                }
                else
                {
                    ViewBag.name = "choose project";
                    ViewBag.desk = "No description";
                    ViewBag.ConnectionName = "ConnectionName";
                    ViewBag.DatabaseName = "DatabaseName";
                    ViewBag.ServerName = "ServerName";
                }

                return View(_projectModel);
            }
            else
            {
                return View(GetExampleProject());
            }

        }

        public ActionResult ListProjectPartial()
        {
            var countInvited = 0;
            if (User.Identity.IsAuthenticated)
            {
                _currentUser = _serviceUser.GetUserByID(User.Identity.GetUserId());
                var projects = _serviceProjectsShareService.GetUserProjects(_currentUser);
                var projectsViewModel = Mapper.Map<IEnumerable<Project>, IEnumerable<ProjectsListViewModel>>(projects).ToList();
                foreach (var project in projectsViewModel)
                {
                    project.CountUsersForShared = _serviceProjectsShareService.GetUsersForSharedProject(_serviceProject.GetProject(project.ProjectID)).Count();
                    project.UserRole = _serviceProjectsShareService.GetUserRole(_currentUser, project.ProjectID);
                    if (project.UserRole == 0)
                    {
                        countInvited++;
                    }
                }
                _projectModel.Projects = projectsViewModel;
                ViewBag.CountInvited = countInvited;

                return PartialView("ListProjectPartial", _projectModel);
            }
            else
            {
                countInvited = 1;
                ViewBag.CountInvited = countInvited;
                return PartialView("ListProjectPartial", GetExampleProject());
            }

        }

        public ActionResult QueryBuilderPartial()
        {
            string PreviousPage = "http://stackoverflow.com/1";
            _currentUser = _serviceUser.GetUserByID(User.Identity.GetUserId());
            if (System.Web.HttpContext.Current != null)
            {
                PreviousPage = System.Web.HttpContext.Current.Request.UrlReferrer.ToString();
            }
            string pattern = "[0-9]+$";
            Regex rgx = new Regex(pattern, RegexOptions.IgnoreCase);
            Match match = rgx.Match(PreviousPage);
            int id = Convert.ToInt16(match.Value);
            _projectModel.IdCurrentProject = id;
            if (id != 0)
            {
                var connectionsCurrentProject = _serviceConnection.GetConnectionDBs(_projectModel.IdCurrentProject);
                _projectModel.ConnectionDbs = Mapper.Map<IEnumerable<ConnectionDB>, IEnumerable<ConnectionsListViewModel>>(connectionsCurrentProject).ToList();

                if (_projectModel.ConnectionDbs.Any())
                {
                    var connect = _projectModel.ConnectionDbs.First();
                    var sqlConnection =
                        $"Data source= {connect.ServerName}; Initial catalog= {connect.DatabaseName}; UID= {connect.LoginDB}; Password= {Rijndael.DecryptStringFromBytes(connect.PasswordDB)};";
                    ViewBag.ConnectionString = sqlConnection;
                }

            }
            else
            {
                return PartialView("QueryBuilderPartial", GetExampleProject());
            }
                return PartialView("QueryBuilderPartial", _projectModel);
        }

        public ProjectViewModel GetExampleProject()
        {
            var proj = new List<ProjectsListViewModel>
                {

                    new ProjectsListViewModel
                    {
                        ProjectID = 1,
                        ProjectName = "Example",
                        ProjectDescription = "This project for demonstration service",
                        UserRole = UserRoleProjectsShareConstants.Owner,
                     }

                };
            var connect = new List<ConnectionsListViewModel>
                {
                    new ConnectionsListViewModel

QueryBuilderASP/QueryBuilderMVC/Views/Workflow/CreateQueryPartial.cshtml
@model QueryBuilderMVC.Models.QueryViewModel

@using (Html.BeginForm())
{
	@Html.ValidationSummary();

	<div>
        <p class="TextField" style="color:black;">
            Name: @Html.EditorFor(x => x.QueryName)
            </p>
	</div>
    <div>
        <p class="TextField" style="color:black; display:none">
            Database: @Html.EditorFor(x => x.ProjectID,
       new { placeholder = Model.ProjectID })

        </p>
    </div>
    <div>
        <p class="TextField" style="color:black;">
            Description: @Html.EditorFor(x => x.Description)
        </p>
    </div>
    <div>
       
        <p class="TextField" style="color:black;display:none">
            Database: @Html.TextBoxFor(x => x.QueryBody)
        </p>
    </div>
}

    <textarea id="textquery" class="prettyprint " style="width:230px; height:200px; margin-left:10px;" >

    </textarea>

<script>
    var s = formatQueryString();

        $("#QueryBody").val(s);
        $("#textquery").append(s);
        $('.ui-dialog-buttonset button').addClass("ui-button ui-corner-all ui-widget button-modal");
        $('.ui-dialog-buttonset button').css('width', 70);
        $('.ui-dialog-buttonset button').css('height', 30);
        //prettyPrint();
</script>

QueryBuilderASP/QueryBuilderMVC/Views/Workflow/DataGridPartial.cshtml
<div id="nodata_jqg" style="display: none; text-align: center; font-weight: bold;">No data for display...<br/></div>

<div id="gridWrapper">
    <table id="jqg"></table>
    <div id="jpager"></div>
</div>

QueryBuilderASP/QueryBuilderMVC/Views/Workflow/DeleteConnectionPartial.cshtml
@model QueryBuilderMVC.Models.ConnectionViewModel


<h5>@Resources.Resource.DeleteConnectionQuestion</h5>
<div>
    <p>@Resources.Resource.CreateConnectionName @Html.DisplayFor(m => m.ConnectionName)</p>
    <p>@Resources.Resource.CreateConnectionDatabase @Html.DisplayFor(m => m.DatabaseName)</p>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <p class="TextField" style="display:none;">Name project: @Html.TextBoxFor(x => x.ConnectionID, new { placeholder = Model.ConnectionID }) </p>
        <p class="TextField" style="display:none;">Name project: @Html.TextBoxFor(x => x.ConnectionOwner, new { placeholder = Model.ConnectionOwner }) </p>
        <p class="TextField" style="display:none;">Name project: @Html.TextBoxFor(x => x.ServerName, new { placeholder = Model.ServerName }) </p>
        <p class="TextField" style="display:none;">Name project: @Html.TextBoxFor(x => x.DatabaseName, new { placeholder = Model.DatabaseName }) </p>
        <p class="TextField" style="display:none;">Name project: @Html.TextBoxFor(x => x.LoginDB, new { placeholder = Model.LoginDB }) </p>
        <p class="TextField" style="display:none;">Name project: @Html.TextBoxFor(x => x.PasswordDB, new { placeholder = Model.PasswordDB }) </p>
        <p class="TextField" style="display:none;">Name project: @Html.TextBoxFor(x => x.ConnectionName, new { placeholder = Model.ConnectionName }) </p>
        @*<input type="submit" value="Delete" />*@
    }
</div>

<script>
        $('.ui-dialog-buttonset button').addClass("ui-button ui-corner-all ui-widget button-modal");
        $('.ui-dialog-buttonset button').css('width', 70);
        $('.ui-dialog-buttonset button').css('height', 30);
</script>

QueryBuilderASP/QueryBuilderMVC/Views/Workflow/DeleteQueryPartial.cshtml
@model QueryBuilderMVC.Models.QueryViewModel


<h5 style="font-size:17px;"><b>@Resources.Resource.DeleteQueryQuestion</b></h5>
<div>
	<p><b>@Resources.Resource.CreateQueryName:</b> @Html.DisplayFor(m => m.QueryName)</p>
	<p><b>@Resources.Resource.CreateQueryBody:</b> @Html.DisplayFor(m => m.QueryBody)</p>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <p class="TextField" style="display:none;">@Html.TextBoxFor(x => x.QueryID, new { placeholder = Model.QueryID }) </p>
        <p class="TextField" style="display:none;">@Html.TextBoxFor(x => x.UserID, new { placeholder = Model.UserID }) </p>
        <p class="TextField" style="display:none;">@Html.TextBoxFor(x => x.ProjectID, new { placeholder = Model.ProjectID }) </p>
		<p class="TextField" style="display:none;">@Html.TextBoxFor(x => x.QueryName, new { placeholder = Model.QueryName }) </p>
		<p class="TextField" style="display:none;">@Html.TextBoxFor(x => x.QueryBody, new { placeholder = Model.QueryBody }) </p>
		<p class="TextField" style="display:none;">@Html.TextBoxFor(x => x.QueryDate, new { placeholder = Model.QueryDate }) </p>

        @*<input type="submit" value="Delete" />*@
    }
</div>

<script>
        $('.ui-dialog-buttonset button').addClass("ui-button ui-corner-all ui-widget button-modal");
        $('.ui-dialog-buttonset button').css('width', 70);
        $('.ui-dialog-buttonset button').css('height', 30);
</script>

QueryBuilderASP/QueryBuilderMVC/Views/Workflow/ListConnectionPartial.cshtml
@model QueryBuilderMVC.Models.ProjectViewModel



@if (Model.IdCurrentProject != 0 && Model.ConnectionDbs!=null)
{
	foreach (var item in Model.ConnectionDbs)
	{

        <div style="width:100%; border-bottom: solid 1px gray; height: 30px;">
            @if (Request.IsAuthenticated)
            {
                <div class="ItemNameConnection">
                    @Html.ActionLink(@item.ConnectionName, "UpdateConnectionPartial", "Workflow", new { id = item.ConnectionID },
                                new
                                {
                                    @class = "LinkEdit",
                                    data_dialog_title = "Update connection"
                                })
                </div>

                <div>
                    @Html.ActionLink(" ", "DeleteConnectionPartial", "Workflow", new { id = item.ConnectionID },
                            new
                            {
                                @class = "DeleteConnectionItem iconHeaderDeleteItem",
                                data_dialog_title = "Delete connection"
                            })
                </div>
                                <div class="">
                                    @Html.ActionLink(" ", "UpdateConnectionPartial", "Workflow", new { id = item.ConnectionID },
                                        new
                                        {
                                            @class = "UpdateConnectionItem",
                                            data_dialog_title = "Update connection"
                                        })
                                </div>
            }
            else
            {
                <div class="ItemNameConnection">
                    @item.ConnectionName
                </div>
            }

            <div>
                @Html.ActionLink(" ", "ERModel", "Builder", new { id = item.ConnectionID },
                                        new
                                        {
                                            @class = "ERModel",
                                            data_dialog_title = "ER-Model",
                                            target = "_blank"
                                        })
            </div>
        </div>
        <br />

    }
}

<script>


    $(document).ready(function () {
        $(function () {

           

            $(".UpdateConnection")
                .prepend("<span class='iconHeaderEdit iconHeader portlet-3'></span>");

            $(".UpdateConnectionItem")
                .prepend("<span class='iconHeaderEditItem iconHeader portlet-3'></span>");

            $(".DeleteConnection")
                .prepend("<span class='iconHeaderDelete iconHeader portlet-2'></span>");
            $(".DeleteConnectionItem")
                .prepend("<span class='iconHeaderDeleteItem iconHeader portlet-2'></span>");
            $(".CreateConnection")
                .prepend("<span class='iconHeaderCreate iconHeader portlet-2'></span>");

            $(".ERModel")
                .prepend("<span class='iconHeaderERModelItem iconHeader portlet-2'></span>");

            $(".portlet-toggle").click(function () {
                var icon = $(this);
                icon.toggleClass("ui-icon-minusthick ui-icon-plusthick");
                icon.closest(".portlet").find(".portlet-content").toggle();
            });
        });
        $.ajaxSetup({ cache: false });
        //CRUD connection
        ModalPostDialogDeleteWithNotifyAndUpdate(".DeleteConnectionItem", '@Url.Action("DeleteConnectionPartial", "Workflow")', '@Url.Action("ListConnectionPartial", "Workflow")', UpdateConnectionList);
        ModalPostDialogUpdateWithNotifyAndUpdate(".UpdateConnectionItem", '@Url.Action("UpdateConnectionPartial", "Workflow")', '@Url.Action("ListConnectionPartial", "Workflow")', UpdateConnectionList);
        ModalPostDialogUpdateWithNotifyAndUpdate(".LinkEdit", '@Url.Action("UpdateConnectionPartial", "Workflow")', '@Url.Action("ListConnectionPartial", "Workflow")', UpdateConnectionList);
       

    });

</script>

QueryBuilderASP/QueryBuilderMVC/Views/Workflow/ListHistoryPartial.cshtml
@model QueryBuilderMVC.Models.ProjectViewModel
@using Newtonsoft.Json
@using Newtonsoft.Json.Converters

@if (Request.IsAuthenticated && Model.IdCurrentProject != 0 && Model.QueryHistory != null)
{
	<div id="HistoryWrapper">

	</div>

	<div id="pager" class="ui-state-default ui-jqgrid-pager ui-corner-bottom" dir="ltr">
		<div id="pg_pager" class="ui-pager-control" role="group">
			<table cellspacing="0" cellpadding="0" border="0" class="ui-pg-table" style="table-layout:fixed;" role="row">
				<tbody>
					<tr>
						<td id="pager_center" align="center" style="width: 260px;">
							<table cellspacing="0" cellpadding="0" border="0" style="table-layout:auto;" class="ui-pg-table">
								<tbody>
									<tr>
										<td id="first_pager" class="ui-pg-button ui-corner-all ui-state-disabled" style="cursor: pointer;">
											<span class="ui-icon ui-icon-seek-first"></span>
										</td>
										<td id="prev_pager" class="ui-pg-button ui-corner-all ui-state-disabled" style="cursor: pointer;">
											<span class="ui-icon ui-icon-seek-prev"></span>
										</td>
										<td class="ui-pg-button ui-state-disabled" style="width:4px;">
											<span class="ui-separator"></span>
										</td>
										<td dir="ltr">
											Page
											<span id="currentPage">2</span>
											of
											<span id="pageСount"></span>
										</td>
										<td class="ui-pg-button ui-state-disabled" style="width:4px;">
											<span class="ui-separator"></span>
										</td>
										<td id="next_pager" class="ui-pg-button ui-corner-all" style="cursor: pointer;"><span class="ui-icon ui-icon-seek-next"></span></td>
										<td id="last_pager" class="ui-pg-button ui-corner-all" style="cursor: pointer;"><span class="ui-icon ui-icon-seek-end"></span></td>
									</tr>
								</tbody>
							</table>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<script type="text/javascript">
	var QueryHistory = @Html.Raw(JsonConvert.SerializeObject(Model.QueryHistory, Formatting.None, new IsoDateTimeConverter() { DateTimeFormat = "M/dd/yyyy HH:mm" }));
	QueryHistory.reverse();
	QueryHistory.QuantityOnPage = 5;
	QueryHistory.PageCount = QueryHistory.length / QueryHistory.QuantityOnPage << 0;
	QueryHistory.CurrentPage = 1;
	$("#pageСount").append(QueryHistory.PageCount);



	$(window).ready(function(){
	    changeHistoryPage(1);
	    RefreshQueryList();
	    RefreshQueryHistoryList();
	});


	</script>
}

QueryBuilderASP/QueryBuilderMVC/Views/Workflow/SendQueryPartial.cshtml
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "emailQueryForm" }))
{
    @Html.ValidationSummary();
    <input type="text" name="query" class="sqlQuery" style="display:none;" value="@ViewBag.Query" />
            <div>
                @Html.Label("E-mail:")
                <div>
                    <input type="email" name="email" required="required"/>
                </div>
            </div>
            <input type="submit" />
}

<script>
        $('.ui-dialog-buttonset button').addClass("ui-button ui-corner-all ui-widget button-modal");
        $('.ui-dialog-buttonset button').css('width', 70);
        $('.ui-dialog-buttonset button').css('height', 30);
</script>

QueryBuilderASP/QueryBuilderMVC/Views/Workflow/Success.cshtml
Success

QueryBuilderASP/QueryBuilderMVC/Views/Workflow/UpdateConnectionPartial.cshtml
@model QueryBuilderMVC.Models.ConnectionViewModel

@using (Html.BeginForm())
{
    @Html.ValidationSummary();

    <div>
        @Html.LabelFor(model => model.ConnectionName)
        <div>
            @Html.EditorFor(x => x.ConnectionName )
        </div>
    </div>
    <div>
        @Html.LabelFor(model => model.ServerName)
        <div>
            @*@Html.LabelFor(model => model.ServerName)*@
            @if (Model.ConnectionCount > 0)
            {
                <div>
                    @Html.TextBoxFor(x => x.ServerName, new { disabled = "disabled", placehoder = Model.ServerName })
                    <p class="TextField" style="display:none;">
                        Database: @Html.TextBoxFor(x => x.ServerName,
                    new { placeholder = Model.ServerName })
                    </p>
                </div>
            }
            else
            {
                <div>
                    @Html.EditorFor(x => x.ServerName)
                </div>
            }
        </div>
    </div>
    <div>
        @Html.LabelFor(model => model.LoginDB)
        <div>
            @Html.EditorFor(x => x.LoginDB)
        </div>
    </div>
    <div>
        @Html.LabelFor(model => model.PasswordDB)
        <div>
            @Html.EditorFor(x => x.PasswordDB)
        </div>
    </div>
    <div>
        @Html.LabelFor(model => model.DatabaseName)
        <div>
            @Html.EditorFor(x => x.DatabaseName)
        </div>
    </div>
    <p class="TextField" style="display:none;">
        Database: @Html.TextBoxFor(x => x.ConnectionOwner,
       new { placeholder = Model.ConnectionOwner })
    </p>
    <p class="TextField" style="display:none;">
        Database: @Html.TextBoxFor(x => x.ConnectionID,
       new { placeholder = Model.ConnectionID })
    </p>
}
<script>
        $('.ui-dialog-buttonset button').addClass("ui-button ui-corner-all ui-widget button-modal");
        $('.ui-dialog-buttonset button').css('width', 70);
        $('.ui-dialog-buttonset button').css('height', 30);
</script>

QueryBuilderASP/QueryBuilderMVC/Views/Workflow/UpdateProjectPartial.cshtml
@model QueryBuilderMVC.Models.ProjectViewModel

@using (Html.BeginForm())
{

    @Html.ValidationSummary();
   
    <p class="TextField" style="display:none;">Name project: @Html.TextBoxFor(x => x.IdCurrentProject, new { placeholder = Model.IdCurrentProject}) </p>

    <p class="TextField">@Resources.Resource.CreateProjectName @Html.TextBoxFor(x => x.Name, new { placeholder = Model.Name }) </p>
    <p class="TextField">@Resources.Resource.CreateProjectDescription @Html.TextBoxFor(x => x.Description, new { placeholder = Model.Description })</p>
    @*<br />

    <input type="submit" name="action" value="Update project" />*@
}

<script>
        $('.ui-dialog-buttonset button').addClass("ui-button ui-corner-all ui-widget button-modal");
        $('.ui-dialog-buttonset button').css('width', 70);
        $('.ui-dialog-buttonset button').css('height', 30);
</script>